#!/bin/bash
prod() {
    echo "access_key = ${AWS_ACCESS_KEY_ID}" >> .s3cfg
    echo "secret_key = ${AWS_SECRET_ACCESS_KEY}" >> .s3cfg
}

if [[ $TRAVIS_PULL_REQUEST != 'false' ]]; then
    echo "This is a pull request. No before script will be done."
elif [[ $TRAVIS_BRANCH == 'master' ]]; then
    prod
else
    echo "Nothing to do..."
fi
